# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mentefria/Documents/experimentos/programa_trabajo/trabajo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(806, 714)
        Dialog.setStyleSheet("background-color: #3a3e47")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 500, 431, 181))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 26pt\"Century Gothic\";\n"
"    color: #f2b824;\n"
"    background-color: #1d1c21;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: #f2c44e;\n"
"    background-color: #3a3c42;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #eb7b13;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 741, 221))
        self.label.setStyleSheet("color: #ccc;\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"text-align: right ")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 280, 781, 191))
        self.textEdit.setStyleSheet("color: #ccc;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: #1d1c21")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "АНАЛИЗИРОВАТЬ"))
